<a href="https://colab.research.google.com/github/rjrocks1908/Machine_learning_tuts/blob/main/NumPy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
mx_1s = np.ones(5)

In [ ]:
print(mx_1s)

[1. 1. 1. 1. 1.]


In [ ]:
#Creating Ones Matrix
mx_1s = np.ones((3,4))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#Creating Ones Matrix with specific data type
mx_1s = np.ones((3,4), dtype = int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
#Creating Zeros Matrix
mx_0s = np.zeros((4,6))
print(mx_0s)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
#Creating Zeros Matrix with specific data type
mx_0s = np.zeros((4,6), dtype=bool)
print(mx_0s)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [ ]:
#Creating Zeros Matrix with str data type which results in the empty string
mx_0s = np.zeros((4,6), dtype=str)
print(mx_0s)

[['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']]


In [ ]:
em_str = ''
print(bool(em_str)) #Empty string is false

False


In [ ]:
#Creating the empty matrix
em_mx = np.empty((3,3))
print(em_mx) # any random value can be present in the empty matrix

[[4.66121155e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]
