<a href="https://colab.research.google.com/github/rjrocks1908/Machine_learning_tuts/blob/main/NumPy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy Functions :**

In [2]:
import numpy as np

**arange()**

In [3]:
#np.arange(start, end, steps)
arr_1d = np.arange(1,13)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [4]:
even_ar = np.arange(1,13,2)
print(even_ar)

[ 1  3  5  7  9 11]


**linspace()**

In [7]:
# np.linspace(start no, end no, number of values)
np.linspace(1,5,45)

array([1.        , 1.09090909, 1.18181818, 1.27272727, 1.36363636,
       1.45454545, 1.54545455, 1.63636364, 1.72727273, 1.81818182,
       1.90909091, 2.        , 2.09090909, 2.18181818, 2.27272727,
       2.36363636, 2.45454545, 2.54545455, 2.63636364, 2.72727273,
       2.81818182, 2.90909091, 3.        , 3.09090909, 3.18181818,
       3.27272727, 3.36363636, 3.45454545, 3.54545455, 3.63636364,
       3.72727273, 3.81818182, 3.90909091, 4.        , 4.09090909,
       4.18181818, 4.27272727, 4.36363636, 4.45454545, 4.54545455,
       4.63636364, 4.72727273, 4.81818182, 4.90909091, 5.        ])

**reshape()**

In [10]:
#it is used to change the dimension of an array for eg- 1D to 2D, 1D to 3D
ar_2d = arr_1d.reshape(2,6)
print(ar_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [11]:
ar_3d = arr_1d.reshape(2,3,2)
print(ar_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [12]:
ar = np.arange(1,13).reshape(2,6)
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


**ravel()**

In [13]:
#it converts multi-dimensional array into 1D array
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

**flatten()**

In [14]:
#it also converts multi-dimensional array into 1D array
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

**transpose()**

In [15]:
#converts rows into columns and columns into rows
ar.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [16]:
ar.T

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])